# Use Node.js image for development
FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the entire Angular project
COPY . .

# Expose the Angular dev server port
EXPOSE 4200

# Start Angular with live-reload
CMD ["npm", "run", "start"]
