version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - postgres/.env
    networks:
      - ottonova
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend_prod
    restart: always
    depends_on:
      - postgres
    env_file:
      - backend/.env
    networks:
      - ottonova
    ports:
      - "3100:3000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend_prod
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ottonova
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  ottonova:
    driver: bridge